### ISSUE TITLE
Does not work with v4 Pelican

### ISSUE THREAD

**Issue by askpatrickw** [xm3ron/pjport#2]
When I attempt to use the theme, I get the error 

> >pelican
> CRITICAL: UndefinedError: '_' is undefined

Not very much information to go on as to what is wrong unfortunately. No additional information with the --verbose flag either.

OS:
    Windows 10

python --version
    Python 3.7.2

pelican --version
    4.0.1

**Comment by Kentoseth** [comment]
@askpatrickw running with `-D` should give you the reason for the error, which is Jinja2 and the issue documented here: https://github.com/getpelican/pelican-themes/issues/460

You can get this theme working again by adding this to your `pelicanconf.py` file:
```
PLUGIN_PATHS = ['/path/to/pelican-plugins']
PLUGINS = ['i18n_subsites', ]
JINJA_ENVIRONMENT = { 
'extensions': ['jinja2.ext.i18n'], 
}
```
(you also need the pelican-plugins installed locally)
